"""数据引擎模块：负责行情数据存储与 baostock 增量同步（Postgres/SQLite）。"""

from typing import Protocol

import pandas as pd

from sequoia_x.core.logger import get_logger
from sequoia_x.db import IntegrityError, connect, ensure_parent_dir

logger = get_logger(__name__)


_CREATE_TABLE_SQL_SQLITE = """
CREATE TABLE IF NOT EXISTS stock_daily (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol   TEXT    NOT NULL,
    date     TEXT    NOT NULL,
    open     REAL,
    high     REAL,
    low      REAL,
    close    REAL,
    volume   REAL,
    turnover REAL,
    UNIQUE (symbol, date)
);
"""

_CREATE_TABLE_SQL_PG = """
CREATE TABLE IF NOT EXISTS stock_daily (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol   TEXT    NOT NULL,
    date     TEXT    NOT NULL,
    open     DOUBLE PRECISION,
    high     DOUBLE PRECISION,
    low      DOUBLE PRECISION,
    close    DOUBLE PRECISION,
    volume   DOUBLE PRECISION,
    turnover DOUBLE PRECISION,
    UNIQUE (symbol, date)
);
"""

_CREATE_INDEX_SQL = """
CREATE INDEX IF NOT EXISTS idx_symbol_date ON stock_daily (symbol, date);
"""

_UPSERT_DAILY_SQL = """
INSERT INTO stock_daily
    (symbol, date, open, high, low, close, volume, turnover)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(symbol, date) DO UPDATE SET
    open = excluded.open,
    high = excluded.high,
    low = excluded.low,
    close = excluded.close,
    volume = excluded.volume,
    turnover = excluded.turnover
"""


def _bs_worker_init() -> None:
    """多进程 worker 初始化：每个进程独立登录 baostock。"""
    import baostock as bs

    bs.login()


def _bs_fetch_one(task: tuple) -> list:
    """多进程 worker：拉取一只股票，完成后立即返回结果。"""
    import baostock as bs

    symbol, bs_code, start, end = task
    results = []
    try:
        rs = bs.query_history_k_data_plus(
            bs_code,
            "date,open,high,low,close,volume,amount",
            start_date=start,
            end_date=end,
            frequency="d",
            adjustflag="1",  # 后复权
        )
        if rs.error_code != "0":
            return results
        while rs.next():
            results.append([symbol] + rs.get_row_data())
    except Exception:
        # 单只股票失败不应阻塞其他任务的进度。
        return []
    return results


class DataSettings(Protocol):
    db_path: str
    start_date: str


class DataEngine:
    """行情数据引擎，负责数据库存储和 baostock 数据同步。"""

    def __init__(self, settings: DataSettings) -> None:
        self.db_path: str = settings.db_path
        self.start_date: str = settings.start_date
        self._init_db()

    def _init_db(self) -> None:
        ensure_parent_dir(self.db_path)
        with connect(self.db_path) as conn:
            ddl = _CREATE_TABLE_SQL_PG if conn.postgres else _CREATE_TABLE_SQL_SQLITE
            conn.execute(ddl)
            conn.execute(_CREATE_INDEX_SQL)
        from sequoia_x.sync.lite_sync import ensure_sync_state

        ensure_sync_state(self.db_path)
        logger.info(f"数据库初始化完成：{self.db_path}")

    def _get_last_date(self, symbol: str) -> str | None:
        with connect(self.db_path) as conn:
            row = conn.execute(
                "SELECT MAX(date) FROM stock_daily WHERE symbol = ?",
                (symbol,),
            ).fetchone()
        return row[0] if row and row[0] else None

    def get_ohlcv(self, symbol: str) -> pd.DataFrame:
        with connect(self.db_path) as conn:
            sql = "SELECT * FROM stock_daily WHERE symbol = ? ORDER BY date"
            if conn.postgres:
                sql = sql.replace("?", "%s")
            df = pd.read_sql(sql, conn.raw, params=(symbol,))
        return df

    def get_recent_ohlcv(self, symbol: str, limit: int = 120) -> pd.DataFrame:
        """读取最近的日线数据，避免策略计算加载完整历史。"""
        if limit <= 0:
            raise ValueError("limit must be greater than zero")

        with connect(self.db_path) as conn:
            sql = """
                SELECT * FROM (
                    SELECT * FROM stock_daily
                    WHERE symbol = ?
                    ORDER BY date DESC
                    LIMIT ?
                ) AS recent
                ORDER BY date
                """
            if conn.postgres:
                sql = sql.replace("?", "%s")
            df = pd.read_sql(sql, conn.raw, params=(symbol, limit))
        return df

    def _upsert_daily_data(self, df: pd.DataFrame) -> int:
        """事务性写入日线数据，不因部分同步失败而删除已有记录。"""
        if df.empty:
            return 0

        columns = ["symbol", "date", "open", "high", "low", "close", "volume", "turnover"]
        rows = list(df[columns].itertuples(index=False, name=None))
        latest: dict[str, tuple[str, str]] = {}
        for symbol, trade_date, *_rest in rows:
            day = str(trade_date)
            previous = latest.get(str(symbol))
            if previous is None:
                latest[str(symbol)] = (day, day)
            else:
                last_date, first_date = previous
                latest[str(symbol)] = (max(last_date, day), min(first_date, day))
        from sequoia_x.sync.lite_sync import _UPSERT_STATE_SQL, ensure_sync_state

        ensure_sync_state(self.db_path)
        with connect(self.db_path) as conn:
            conn.executemany(_UPSERT_DAILY_SQL, rows)
            conn.executemany(
                _UPSERT_STATE_SQL,
                [
                    (symbol, last_date, first_date, None, None)
                    for symbol, (last_date, first_date) in latest.items()
                ],
            )
            conn.commit()
        return len(rows)

    @staticmethod
    def _to_baostock_code(symbol: str) -> str:
        """将纯数字代码转为 baostock 格式：6/9开头 -> sh，其余 -> sz。"""
        prefix = "sh" if symbol.startswith(("6", "9")) else "sz"
        return f"{prefix}.{symbol}"

    # ── 数据同步 ──

    def sync_today_bulk(self) -> int:
        """先同步股票池，再按缺口增量补日 K。"""
        from sequoia_x.sync.lite_sync import run_market_sync

        result = run_market_sync(
            self.db_path,
            mode="incremental",
            start_date=self.start_date,
        )
        logger.info(result.get("message") or "增量同步完成")
        return int(result.get("written") or 0)

    def backfill(self, symbols: list[str]) -> None:
        """通过 baostock 批量回填历史日 K 线数据（后复权）。

        容错机制：
        - 单只股票失败自动重试 3 次，间隔递增（2s/4s/8s）
        - 每 200 只股票自动重连 baostock（防止长连接超时）
        - 已入库的自动 skip，中断后可重跑续传
        """
        import time
        from datetime import date, timedelta

        import baostock as bs

        today_str = date.today().strftime("%Y-%m-%d")
        max_retries = 3
        reconnect_interval = 200  # 每处理 N 只股票重连一次

        def _login():
            lg = bs.login()
            if lg.error_code != "0":
                logger.error(f"baostock 登录失败: {lg.error_msg}")
                return False
            return True

        if not _login():
            return

        success = 0
        skipped = 0
        failed = 0
        since_reconnect = 0

        try:
            for i, symbol in enumerate(symbols):
                last_date = self._get_last_date(symbol)
                if last_date and last_date >= today_str:
                    skipped += 1
                    if (i + 1) % 500 == 0:
                        logger.info(
                            f"已处理 {i + 1}/{len(symbols)}，"
                            f"成功 {success} 跳过 {skipped} 失败 {failed}"
                        )
                    continue

                # 定期重连，防止长连接超时
                since_reconnect += 1
                if since_reconnect >= reconnect_interval:
                    bs.logout()
                    time.sleep(1)
                    if not _login():
                        logger.error("重连失败，终止回填")
                        return
                    since_reconnect = 0

                start = last_date or self.start_date
                if last_date:
                    start = (date.fromisoformat(last_date) + timedelta(days=1)).strftime("%Y-%m-%d")

                bs_code = self._to_baostock_code(symbol)

                # 带重试的查询
                rows = []
                query_ok = False
                for attempt in range(max_retries):
                    try:
                        rs = bs.query_history_k_data_plus(
                            bs_code,
                            "date,open,high,low,close,volume,amount",
                            start_date=start,
                            end_date=today_str,
                            frequency="d",
                            adjustflag="1",  # 后复权
                        )

                        if rs.error_code != "0":
                            raise RuntimeError(rs.error_msg)

                        rows = []
                        while rs.next():
                            rows.append(rs.get_row_data())
                        query_ok = True
                        break

                    except Exception as exc:
                        if attempt < max_retries - 1:
                            wait = 2 ** (attempt + 1)
                            logger.warning(
                                f"[{symbol}] 第{attempt + 1}次失败: {exc}，{wait}s 后重试"
                            )
                            time.sleep(wait)
                            # 重连 baostock
                            bs.logout()
                            time.sleep(1)
                            _login()
                        else:
                            logger.warning(f"[{symbol}] {max_retries}次重试均失败，跳过")

                if not query_ok:
                    failed += 1
                    continue

                if not rows:
                    skipped += 1
                    continue

                df = pd.DataFrame(rows, columns=rs.fields)
                for col in ["open", "high", "low", "close", "volume", "amount"]:
                    df[col] = pd.to_numeric(df[col], errors="coerce")
                df = df.dropna(subset=["close"])
                df = df[df["volume"] > 0]

                if df.empty:
                    skipped += 1
                    continue

                df["symbol"] = symbol
                df = df.rename(columns={"amount": "turnover"})
                df = df[["symbol", "date", "open", "high", "low", "close", "volume", "turnover"]]

                try:
                    self._upsert_daily_data(df)
                except IntegrityError:
                    pass

                success += 1

                if (i + 1) % 500 == 0:
                    logger.info(
                        f"已处理 {i + 1}/{len(symbols)}，"
                        f"成功 {success} 跳过 {skipped} 失败 {failed}"
                    )

        finally:
            bs.logout()

        logger.info(f"回填完成 — 成功: {success} | 跳过: {skipped} | 失败: {failed}")

    # ── 股票列表 ──

    def get_all_symbols(self) -> list[str]:
        """通过 baostock 获取全市场 A 股代码列表。"""
        import baostock as bs

        lg = bs.login()
        if lg.error_code != "0":
            logger.error(f"baostock 登录失败: {lg.error_msg}")
            return []

        try:
            rs = bs.query_stock_basic(code_name="", code="")
            symbols = []
            while rs.next():
                row = rs.get_row_data()
                code = row[0]           # "sh.600000" or "sz.000001"
                status = row[4]         # "1" = 上市
                stock_type = row[5]     # "1" = 股票
                if status == "1" and stock_type == "1":
                    symbols.append(code.split(".")[1])  # 提取纯数字代码
            logger.info(f"获取股票列表完成，共 {len(symbols)} 只")
            return symbols
        except Exception as e:
            logger.error(f"获取股票列表失败: {e}")
            return []
        finally:
            bs.logout()

    def get_local_symbols(self) -> list[str]:
        with connect(self.db_path) as conn:
            rows = conn.execute(
                "SELECT DISTINCT symbol FROM stock_daily"
            ).fetchall()
        return [row[0] for row in rows]
